// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARfnRB0GCw6HKcnR1MV0PckLPzVeWRJxY',
    appId: '1:933682468146:web:8c6e4b764ac1deea1a732b',
    messagingSenderId: '933682468146',
    projectId: 'mindfulposture',
    authDomain: 'mindfulposture.firebaseapp.com',
    storageBucket: 'mindfulposture.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO7uDTdNUbA1QauAs39C68xs1gf71dTDo',
    appId: '1:933682468146:android:a4dcb9154f35283d1a732b',
    messagingSenderId: '933682468146',
    projectId: 'mindfulposture',
    storageBucket: 'mindfulposture.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCScs2PpcVjwXgFjJ11eXSiXxPVVssK9GQ',
    appId: '1:933682468146:ios:1a9bba8ef5adc1711a732b',
    messagingSenderId: '933682468146',
    projectId: 'mindfulposture',
    storageBucket: 'mindfulposture.firebasestorage.app',
    iosBundleId: 'com.example.mindfulPosture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCScs2PpcVjwXgFjJ11eXSiXxPVVssK9GQ',
    appId: '1:933682468146:ios:1a9bba8ef5adc1711a732b',
    messagingSenderId: '933682468146',
    projectId: 'mindfulposture',
    storageBucket: 'mindfulposture.firebasestorage.app',
    iosBundleId: 'com.example.mindfulPosture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARfnRB0GCw6HKcnR1MV0PckLPzVeWRJxY',
    appId: '1:933682468146:web:0afd5be55b53f23c1a732b',
    messagingSenderId: '933682468146',
    projectId: 'mindfulposture',
    authDomain: 'mindfulposture.firebaseapp.com',
    storageBucket: 'mindfulposture.firebasestorage.app',
  );
}
